### ISSUE TITLE
Add ability to have multiple presenters per talk. 

### ISSUE THREAD

**Issue by logston** [PyGotham/pygotham#100]

**Comment by djds23** [comment]
Can I snag this ticket?

**Comment by dirn** [comment]
@djds23 please do

**Comment by djds23** [comment]
Should multiple presenters be represented by multiple users? Should each of them have to agree to the video release? Should we require co-presenters have their own pygotham account? with a bio and everything? my gut says no. 

IE: right now we have a talk related to a user record, typically the user who created the talk. We can keep this, but I think it makes the most sense to give the presenter its own model, something similar to the user like:
```python
class Presenter(db.Model):
    email = db.Column(db.String(255), unique=True, nullable=True)
    twitter_handle = db.Column(db.String(255), unique=True, nullable=True)
    name = db.Column(db.String(255), unique=True, nullable=False)
    talk = db.Column(
        db.Integer, db.ForeignKey('talk.id'), nullable=False,
    )
    talk = db.relationship(
        'Talks', backref=db.backref('presenters', lazy='dynamic'),
    )
    user = db.Column(
        db.Integer, db.ForeignKey('user.id'), nullable=True,
    )
    user = db.relationship(
        'User', backref=db.backref('presenters', lazy='dynamic'),
    )
```
and allow one person to handle create the talk/form and have the them enter in this data if they have they have a co-presenter. @dirn / @jonafato, thoughts? is this too complicated? We can also just ask for an email and a name and save these in a big old JSON field. That would be far simpler and easier.

**Comment by dirn** [comment]
Simple is better. The more steps we add to the process of submitting a talk, the less likely people become to submit talks.

The simplest route I can think of is to add a text field that just accepts a list of names. This may be too simple, though. It's prone to typos and doesn't give co-presenters a profile page that lists their talks. It also doesn't provide a way to collect contact information for co-presenters. This would be important in case we ever couldn't get in touch with a presenter.

Anything more than this, though, and a pygotham.org account will be required. That isn't necessarily a bad thing.

If a co-presenter doesn't want to set up a speaker profile on the site, there is no reason the person submitting the proposal can't just like any co-presenters in the description. That's how it worked last year.

If, however, a co-presenter wants a speaker profile page, they need a speaker profile.

People submitting a proposal can add co-presenters by searching for speakers' names*. This can either be a list of all users or only those with a complete speaker profile.

This approach can be handled using a `CoPresenter` model that acts as a join table between `Talk` and `User`.

I think anything more than this is too complicated. There's a chance, though, that I'm missing the original intent. @logston can you please update the issue to reflect how you'd like to see this work?

*Are there any privacy concerns with exposing names like this? Currently the only names we expose of those of presenters. Anyone else registered for the site is kept private.

**Comment by logston** [comment]
I really like the idea of each presenter having their own account. If they want to be listed on the site as a co speaker, I don't think it's too much to ask to have them fill out an email and pw form. We would create the record in our db to associate a second speaker with a talk. In order to notify people that such an option exists, I was thinking of having a link (on the CFP form page) to a info page that essentially says 

> Have your co-speaker get an account and then email paul or sarah to link them to the talk.

My schema in mind:

- Users table
- Talk table (no user id column)
- UserTalk table (only constraint is any (user_id, talk_id) combination would have to be unique). Many to many I believe. 

I've chatted with @djds23 about this and he seems to be cool with building it. Thanks @djds23!

**Comment by dirn** [comment]
I'm a little unclear on a few things here.

Why would the users send an email? Why wouldn't the person entering the proposal just add the user themselves? If the co-presenter isn't registered when the user first enters the talk, they can always go back and edit it.

Why is `user_id` being removed from `Talk`? This will lead to really messy code inside `TalkSubmissionForm` and the `talks.proposal` endpoint. I'm not a fan of this approach.

**Comment by jonafato** [comment]
Removing `user_id` from `Talk` will also lead to some messy schema constraints. Can we treat `Talk.user_id` as the primary presenter and allow them to add secondary presenters as needed? Generally, we only expect one presenter in the majority of cases.

**Comment by logston** [comment]
@dirn I figure build in the ability to add a co-presentor would be quite a bit more work. Having me just enter a new row in a db is much simpler to do, especially since there are only a few people who do this. 

@dirn & @jonafato 
Since a user can have multiple talks and multiple users can be associated with a talk, my gut says use a many to many relationship. 

I looked at the code in `pygotham/frontend/talks.py` and I don't think it would be too much to replace the check on line 70 (https://github.com/PyGotham/pygotham/blob/ee561c8a11f33f7ef4aa62e4cc22fd29e947e432/pygotham/frontend/talks.py#L70) with something like:

```
if current_user not in talk.users
```

Also, I feel like each co-presentor should have equal permissions to edit their talk. I understand that each co-presentor can have these permissions almost regardless of the way we change the code. But, having the logic that checks to see if a co-presentor has permission to edit a talk be the same logic that checks to see if the talk creator can edit a talk feels right to me. 

Ie. For each user, check "Is this talk in your list of talks" instead of:

For talk creator:
         You can edit this talk
For talk co-presentor:
         Are you in a third table listing talks and co-presentors

Finally, I feel the aim of this project is to build a framework for other conferences to use. I feel the many to many solution is what most new users would expect this relationship be.

**Comment by dirn** [comment]
In the interest of getting this implemented as part of 2015, switching to a many-to-many isn't going to happen. I don't think we'll have it done by the 1st -- there are too many pieces that need to be touched -- and I'm not a fan of performing this type of data migration once the CFP is live.

For 2015, let's move ahead with the table as-is for the primary speaker and the join table for co-presenters. `talk.users` can still work the way it would with the new approach. 

We can revisit after the conference is over.

**Comment by djds23** [comment]
conference is over, lets revisit this!

**Comment by djds23** [comment]
To start, lets look at how PyCon does it:

https://us.pycon.org/2015/schedule/presentation/381/

You can see here that presentation 381 has two presenters associated with it:

https://us.pycon.org/2015/speaker/profile/172/
https://us.pycon.org/2015/speaker/profile/173/

That being said, if we look at the profiles associated with those speakers, they only have a name, a short bio and the list of presentations associated with user. 

I think the behavior should be:

```
Main Speaker (an already registered User) navigates to `/<eventslug>/talks/new/` ->

Main Speaker provides Title, Description && Duration ->
	
	IF the are co presenters ->
		
		User providers details bio for co presenters 
			* this could be stored as a PresenterProfile record with these three non-nullable fields
				- name
				- email
				- short bio
			* We can send an email to the co-presenter notifying them that they have been submitted. This email can contain a registration URL.

Main Speaker fills out addiditonal notes for the organizers, checks recording release & submits the talk.

If no more action is taken, the co-presenter never registers:

	* we can reference the Main Speaker PresenterProfile, and link to it as:
		- `/<eventslug>/talks/<talkid>/speakers/presenter-profile/<presenterprofileid>`

If the co-presenter creates a User:

	* deactivate (or delete) PresenterProfile
	* link to the new users on detail page
```

Note:
* Presenters should be able to create co-presenters for existing talks

This can be built into the current system as follows:
	- Create a PresenterProfile Model, with 3 string fields, an ID, a delete_ts (or active Boolean)
	- Create a PresenterProfileTalk table to connect N PresenterProfiles to Talks
	- Create a UserTalk join table to connect N users to Talks
	- A presenter_profile route in pygotham/frontend/speakers.py
	- refactor `detail.html` to grab presenters from the join tables
	- add `/<eventslug>/talks/<talkid>/co-presenter/new` endpoint to add new co-presenter

WHAT D'YA THINK?

**Comment by dirn** [comment]
From a legal standpoint, do co-presenters need to sign the recording release? Would we be able to handle it in such a way that accepting to be a co-presenter means you waive your ability to reject the release if the presenter signs it?

**Comment by jonafato** [comment]
I think we should require releases from all presenters for a talk. Any message we include (e.g. "Your talk's main presenter has agreed to our recording release. If you don't agree, don't sign on as a copresenter.") should be equally doable as a checkbox granting permission. Then, the release status for a talk is `all(presenter.recording_release for presenter in talk.presenters)`. This has two important properties:

1. We don't currently require recordings for anyone giving a talk. Waiving the ability of a copresenter to reject the recording release changes things for just that case. This would create a detrimentally inconsistent policy.

2. Having only the presenter that submitted the talk on the website be considered creates a class of speakers whose recording release preferences are ignored, and that's not very fair. Keeping a release for each speaker and collecting them up into a resulting permission lets everyone opt out. (Note: this isn't ideal to those who would like their talks recorded but are blocked by their copresenters, but I don't think the job of conference organizers is to coerce anyone to share their talk via video. This should be encouraged, but speakers expect the choice, and we should honor that.)

**Comment by djds23** [comment]
FLOW based off slack with @jonafato :

1. user creates talk
2. user adds a copresenter’s email address (not publicly visible yet)
3. system sends out email to copresenter to confirm or deny that they are part of this presentation
4. if confirmed, the second speaker becomes visible

The least complex way to handle this would probably be three models and a many to many relationship:

Talk <-> Speaker <-> User

**Speaker**:
 - id (PK)
 - talk (FK)
 - user (FK)
 - recording_release (Boolean)
 - confirmed_ts (DateTime)
 - declined_ts (DateTime)

We should also have a SpeakerInvite so we can resend emails / perform extra communication if the first email does not get delivered. The SpeakerInvite can also hold the claimable token that we can match back to a speaker with a proper user. 

**SpeakerInvite**
 - id (PK)
 - talk (FK)
 - claim_token (String)
 - invited_email (String)

What needs to be added:
 - Emails for Extra Speakers field in the talk `/new` view.
 - Create Speaker associations for speaker when `/new` is submitted, and SpeakerInvite associations for emails to claim
 - ability to accept/reject proposal (set declined_ts) & recording release (set recording_release)
 - A way to convert a SpeakerInvite to a Speaker, must allow Users with emails that mismatch SpeakerInvites to be created
 
@jonafato & @dirn I agree on the recording_release policy

**Comment by djds23** [comment]
Work in progress: https://github.com/djds23/pygotham-1/tree/GITHUB-100-add-speaker-model

Not going to do much work on this tonight. But I look forward to making progress over the week.

**Comment by jonafato** [comment]
@djds23 If you open up a work-in-progress PR, we can comment on changes as they happen to make sure everyone's on the same page.
