### ISSUE TITLE
Color scheme

### ISSUE THREAD

**Issue by dirn** [PyGotham/pygotham#103]
We need to pick the color scheme to use for the site. This includes the primary color and two to three accent colors.

**Comment by jonafato** [comment]
Concept art:

- Logo for website use:
![spotlightlogojustsnake](https://cloud.githubusercontent.com/assets/392720/7218020/7a7bd9d2-e622-11e4-9b34-e96bc399d9ea.jpg)

- Expanded design for use with promotional materials:
![spotlightlogo](https://cloud.githubusercontent.com/assets/392720/7218023/927b90ae-e622-11e4-99ea-cf1f207acd1d.jpg)

Color suggestions coming soon, likely a dark header and a light body and similar tones as the above designs. Big thanks to Jessie for putting this together. Feedback welcome.

**Comment by jonafato** [comment]
More concept art (information including sponsor logos are strictly placeholders and data from last year):

- Homepage
![pygotham2015home](https://cloud.githubusercontent.com/assets/392720/7243972/b3b25330-e7a2-11e4-8caf-2e3d7a1ba3ff.jpg)

- Other (textual) pages
![pygotham2015faq](https://cloud.githubusercontent.com/assets/392720/7243984/d13a0ea2-e7a2-11e4-8a19-bb022b1cb225.jpg)

Implementation should follow these suggestions but does not need to be pixel-perfect.

**Comment by dirn** [comment]
For future reference: http://www.google.com/fonts/specimen/Titillium+Web

**Comment by dirn** [comment]
@jonafato can you get CSS-friendly values for the colors?

**Comment by jonafato** [comment]
Dark Navy: #182833
Light Blue: #D0EAF4
Medium Teal: #376B7A
Yellow: #ACA034

**Comment by dirn** [comment]
Is the "PYGOTHAM 2015" text done in the same light blue?

**Comment by jonafato** [comment]
That's the base, but the graphic has a luminescent effect on it. Graphic below:
![pythonbanner](https://cloud.githubusercontent.com/assets/392720/7312343/1232f006-ea17-11e4-8383-a4877d9670be.png)

**Comment by dirn** [comment]
Ah, that part isn't likely to change, so the graphic works. What about the text with the dates?

**Comment by jonafato** [comment]
That's our teal: #376B7A. This is also the background of the login button, the section titles, and the navbar text.

**Comment by dirn** [comment]
Cool. It's easier to tell for things that are solid blocks. Thanks.

**Comment by jonafato** [comment]
For use in the header:
![circlelogolarger](https://cloud.githubusercontent.com/assets/392720/7373514/f8634a72-ed9a-11e4-9b53-78b6a986f743.png)
We can render whatever different sizes we need for the templates.
