### ISSUE TITLE
Add Contributing Instructions

### ISSUE THREAD

**Issue by jonafato** [PyGotham/pygotham#119]
We currently have no instructions on how to contribute to the project. At minimum, we should provide instructions for forking and submitting pull requests.

**Comment by dirn** [comment]
In addition to adding a `CONTRIBUTING.rst` file, I'd like to see us add a `docs` folder with proper documentation (using Sphinx) that includes guidelines for contributing. `CONTRIBUTING.rst` can refer people to the contributing page in the docs.
