### ISSUE TITLE
Remove login / signup links when there is no current event

### ISSUE THREAD

**Issue by jonafato** [PyGotham/pygotham#123]
If a current event isn't found, the site is largely an archive of past events. Once an event is no longer "current" (and possibly after some grace period), we should remove these links. This mirrors the desired behavior of the historical archive static site that will eventually take its place.

**Comment by dirn** [comment]
If we ever want to send out email updates like "hey, this year's CFP opens on whatever day," we probably want to let people register all year long. That said, I think your thinking makes sense.

**Comment by jonafato** [comment]
Good point. I think there's still some value in the concept, and we may find a way to balance the two in the future. I'm going to leave this open, put it on hold, and think on it for a while.
