### ISSUE TITLE
Eventbrite integration

### ISSUE THREAD

**Issue by dirn** [PyGotham/pygotham#129]
This should include
- [ ] ticket status
- [ ] discount code generation
- [ ] sponsor ticket generation
- [ ] scholarship ticket generation

**Comment by jonafato** [comment]
The [official Python client](https://pypi.python.org/pypi/eventbrite/3.0.5) supports our version of Python this time around.

**Comment by dirn** [comment]
This is on hold until the next release of the SDK, The most recent release (3.1.0) uses `dict.has_key` which doesn't exist anymore.

**Comment by dirn** [comment]
Still on hold waiting for Eventbrite to resolve their 500 errors. (I haven't checked in a week so this may be resolved.)
