### ISSUE TITLE
Update "Submit a Talk" form

### ISSUE THREAD

**Issue by logston** [PyGotham/pygotham#131]
I think we should add the following optional field:
- twitter handle

I think we should remove the following fields:
- Abstract 
- Objectives
- Target Audience
- Outline
- Type  (Type should be assumed to be a talk. Tutorials will be manually entered by Staff (Paul))

I think the options for Duration should be 25 minute and 55 minute.

**Comment by dirn** [comment]
We can definitely remove Objectives, Target Audience, and Outline. After the decision to change the duration options, Type will definitely go away and default to "talk."

I think a case can be made to keep Abstract, provided we describe it better. It's already optional and about 75% of talks submitted in 2014 have an abstract that is filled in and is different from the description.

    # SELECT (SUM(x) * 100) / (SUM(y) * 100) AS pct FROM (
    SELECT COUNT(1) AS x, 0 AS y FROM talks WHERE abstract NOT IN ('', description)
    UNION
    SELECT 0 AS x, COUNT(1) AS y FROM talks
    ) AS talks;
              pct
    ------------------------
     0.74074074074074074074

That said, in the interest of lowering the barrier of entry for first-time submitters, let's take it out.

**Comment by logston** [comment]
Nice research. Sounds good to me.

On Thu, Apr 23, 2015 at 11:40 PM, Andy Dirnberger <notifications@github.com>
wrote:

> We can definitely remove Objectives, Target Audience, and Outline. After
> the decision to change the duration options, Type will definitely go away
> and default to "talk."
>
> I think a case can be made to keep Abstract, provided we describe it
> better. It's already optional and about 75% of talks submitted in 2014 have
> an abstract that is filled in and is different from the description.
>
> # SELECT (SUM(x) * 100) / (SUM(y) * 100) AS pct FROM (
> SELECT COUNT(1) AS x, 0 AS y FROM talks WHERE abstract NOT IN ('', description)
> UNION
> SELECT 0 AS x, COUNT(1) AS y FROM talks
> ) AS talks;
>           pct
> ------------------------
>  0.74074074074074074074
>
> That said, in the interest of lowering the barrier of entry for first-time
> submitters, let's take it out.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PyGotham/pygotham/issues/131#issuecomment-95789807>.
>



-- 
Paul Logston
plog.paullogston.com
github.com/logston

**Comment by djds23** [comment]
I unless someone else has beat me to it, I will address this in my fix for #100 since they seem to be related

**Comment by djds23** [comment]
it looks like someone DID beat me to it in #133

**Comment by dirn** [comment]
@djds23 :+1: 

Please do them as separate pull requests, though. While they touch the same pieces of the code, the changes themselves are unrelated.

#133 only addressed how to set new durations. It didn't address any of the other fields.

**Comment by djds23** [comment]
as a note, a talk with no 'type' on it will look funky in the `/profile/dashboard` view.

![screen shot 2015-04-28 at 8 36 09 pm](https://cloud.githubusercontent.com/assets/5833968/7383049/3fdd0e6a-ede6-11e4-9957-999854e7dd27.png)

**Comment by dirn** [comment]
Good point. Take it out.

**Comment by dirn** [comment]
This was closed by #143.
