### ISSUE TITLE
Include event identifier at beginning of all URLs

### ISSUE THREAD

**Issue by dirn** [PyGotham/pygotham#135]
In order to provide permanent URLs for event-related content, there needs to be a way to select a specific event for viewing. This should be done by passing an identifier -- in the case of PyGotham this will be the year -- at the beginning of all URLs. What needs to be done to make this work?

- [x] A `slug` field should be added to the `Event` model. It should default to a value generated based on `Event.name`.
- [x] A `<slug>` parameter should be added to all URLs associated with the frontend app.
- [x] A function needs to be added to the events package that can be used to load the viewed event anywhere in the project. This could potentially be `events.get_current`.
- [x] Any place that `events.get_current` is used should be updated to use this new function (unless the function replaces the current `events.get_current`).

**Comment by jonafato** [comment]
Related to #88

**Comment by dirn** [comment]
Relevant: http://flask.pocoo.org/docs/0.10/patterns/urlprocessors/

**Comment by jonafato** [comment]
Fixed by #153. Current event is now accessible via `flask.g.current_event`.
