### ISSUE TITLE
Add ability for speakers to provide a link to slides or other online talk materials

### ISSUE THREAD

**Issue by logston** [PyGotham/pygotham#174]
During/after the conference, attendees often ask if we have slides for the talks. Collecting slides from speakers is often like herding cats. Things are further complicated by the fact that speakers don't all use materials that can be hosted on a site like Speaker Deck.

Building a generic material hosting service is a bit beyond what pygotham.org should offer. Instead, we should allow speakers to provide a URL to their slides or other online materials. This should be exposed on the talk detail page along with the video URL. Unlike the video URL, however, it should be editable through the user's dashboard.

**Comment by dirn** [comment]
What's the goal here?

**Comment by dirn** [comment]
I'm closing this issue until it's been updated to contain a spec.
