### ISSUE TITLE
Important dates should have strftime configurable displays

### ISSUE THREAD

**Issue by jonafato** [PyGotham/pygotham#193]
Previous title: CFP close date should include time (and possibly timezone)

Making this configurable removes ambiguity when necessary without forcing a specific format for all deployments.

**Comment by masterp4dev** [comment]
Hi @jonafato, I would like to jump on this. Any heads up?

**Comment by jonafato** [comment]
@masterp4dev feel free to open a PR for this issue. My thinking here was that this format setting would be used in templates anywhere we currently show deadlines.
