### ISSUE TITLE
Remove password setting logic introduced in #80

### ISSUE THREAD

**Issue by jonafato** [PyGotham/pygotham#201]
Pull request #80 added logic to set a password for a user created through the admin site. This was added to address a bug / defect in Flask-Security's handling of password reset tokens. As of mattupstate/flask-security#389, this is no longer necessary, so the password setting step should be removed (the reset link should still be sent).

**Comment by crazcalm** [comment]
Is this ticket still up for grabs?

**Comment by dirn** [comment]
@crazcalm go for it!

**Comment by jonafato** [comment]
This issue is blocked by #317. Once that is resolved, a fix can be applied.
