### ISSUE TITLE
Should we use Flask-Menu?

### ISSUE THREAD

**Issue by dirn** [PyGotham/pygotham#219]
[Flask-Menu](http://flask-menu.readthedocs.org) is probably a simpler way to handle the changes introduced in 0418bda to address site navigation.

**Comment by jonafato** [comment]
I looked into using Flask-Menu here, and I found it to be different from how I'd like it to work. For this reason, I wrote [Flask-Copilot](https://flask-copilot.rtfd.org). I'm proposing that we use it here and open to any feedback, including reasons why we shouldn't.

**Comment by dirn** [comment]
I don't have the experience with Flask-Menu (and the others) to speak to their strengths and weaknesses, but I'm on board with using Flask-Copilot. I like the idea of removing the redundancy required by Flask-Menu.
