### ISSUE TITLE
Update 'Additional Notes' section of talk submission form to include 'time of conference' pref.

### ISSUE THREAD

**Issue by logston** [PyGotham/pygotham#221]
Some speakers have time constraints they have to work around when attending PyGotham. 

It'd be great to have a field on the talk submission form where a user could select the time they'd prefer to give a talk. That way we can take that info into account when building the schedule.

**Comment by dirn** [comment]
[They can already do this.](https://github.com/PyGotham/pygotham/blob/6e3240d1daa1888305832cfd4ed694bd7addd66f/pygotham/talks/forms.py#L52-L60)

**Comment by logston** [comment]
```python
                'description': (
                    "Any other information you'd like the program committee "
                    "to know, e.g., additional context and resources, "
                    "previous speaking experiences, etc. This will not be "
                    "shared publicly."
                ),
```

==> 

```python
                'description': (
                    "Any other information you'd like the program committee "
                    "to know, e.g., additional context and resources, "
                    "previous speaking experiences, preferences for when you"
                    " would like to speake,  etc. This will not be shared publicly."
                ),
```

**Comment by logston** [comment]
Second thought, I think I would still like a new field because I'd like to have the data to build a schedule generator (a generator that churns out possible schedules). And I'd rather not parse the `additional_requirements` field for such data.

**Comment by jonafato** [comment]
This field is useful once we have a technical solution to this (probably intractable) social problem. Once such a solution exists, the input can be easily added. I'm going to close this for now as on hold and reopen it once we have the backend that will use the data.
