### ISSUE TITLE
Automate speaker email and announcement tweet

### ISSUE THREAD

**Issue by dirn** [PyGotham/pygotham#245]
We currently manually email a speaker when their talk is accepted. He also (at least intend to) tweet about it. This should be an easy thing to automate, and it removes work from the organizers' workflow and ensures that this step is not forgotten for any speakers.

Issue #244 presents a similar process for sponsors.

One possible twist on this is that we may wish to batch these so that all speakers find out at once (both acceptance and rejection) rather than finding out in a rolling fashion. (I believe these actions are exposes as bulk actions through the admin, so that may take care of the batching.)

**Comment by jonafato** [comment]
I think this is actually a two step process:

1. When a speaker's talk is accepted by the speaker committee, we should notify that speaker automatically. As noted above, this should potentially be batched and be triggered by some "I'm done marking talks as accepted, send the emails now" button.
2. When a speaker actually confirms that they're able to speak, a public message should go out via Twitter.

**Comment by dirn** [comment]
That's a good point. I forgot about the possibility that a speaker could withdraw.
