### ISSUE TITLE
Disable the runserver management command

### ISSUE THREAD

**Issue by djds23** [PyGotham/pygotham#256]
If `python manage.py runserver` does not actually run the server, we should probably remove it

**Comment by dirn** [comment]
What is the problem with `runserver`? It's part of Flask-Script, so you'd probably have to do whatever there.

**Comment by djds23** [comment]
@dirn when I run `python wsgi.py`, and I hit `localhost:500/<slug>`, it resolves. However when I run `python manage.py runserver` and hit the same endpoint, I get a 404. Not positive what the problem is yet, but figured there is a larger issue at play.

**Comment by jonafato** [comment]
There are a few differences between what `python manage.py runserver` and `python wsgi.py` do. Specifically, we need to at least `frontend.create_app()` inside `runserver` to get things working. If we keep the `runserver` command around, we should probably just wrap what `wsgi.py` already does. It's probably better to remove the command entirely, though, for the sake of having one entry point. We can do this by passing `with_default_commands=False` to the `Manager` init method, but we'll need to reregister the `shell` command (these two seem to be coupled together).

**Comment by dirn** [comment]
Ah, yes. I believe that's because `wsgi.py` uses `DispatcherMiddleware` to load the `frontend` app, wheres `manage.py` creates its own app.

**Comment by jonafato** [comment]
The docs for disabling the default commands are just below the docs for the [`shell`](https://flask-script.readthedocs.org/en/latest/#shell) command. The `shell` command docs explain how to add it back once default commands are removed.

**Comment by jonafato** [comment]
This is fixed by #264.
