### ISSUE TITLE
DuckDuckGo Search results broken by `2016` subdomain

### ISSUE THREAD

**Issue by djds23** [PyGotham/pygotham#282]
When I search pygotham on DuckDuckGo, the first link is for: 
https://pygotham.org/2015/

This redirects to:
https://2016.pygotham.org/2015/

which responds with a 404:
<img width="1275" alt="screen shot 2016-04-12 at 2 45 39 pm" src="https://cloud.githubusercontent.com/assets/5833968/14471583/4346f1ca-00bd-11e6-934e-db4fbb975a6d.png">

Original search results:
<img width="1016" alt="screen shot 2016-04-12 at 2 42 42 pm" src="https://cloud.githubusercontent.com/assets/5833968/14471594/4dc8a4ae-00bd-11e6-8af5-8bc944d5281d.png">

As a note, this does not break google.
<img width="1276" alt="screen shot 2016-04-12 at 2 47 16 pm" src="https://cloud.githubusercontent.com/assets/5833968/14471645/85782b40-00bd-11e6-9644-68fe13543483.png">

Not sure we want to do something about this, but figured it was worth reporting @dirn / @jonafato

**Comment by dirn** [comment]
Have you reached out to Duck Duck Go?

**Comment by djds23** [comment]
@dirn nope

**Comment by djds23** [comment]
@dirn not sure of the exact avenue to do that

**Comment by dirn** [comment]
I'm not really sure what to do other than say "wait for Duck Duck Go to catch up." The 2016 site has been live for about 10 days. We're using a 301 from `pygotham.org` to the current event. Duck Duck Go is technically doing the correct thing here. But I think Google is acknowledging that people abuse 301s for stuff like this.

**Comment by dirn** [comment]
We could potentially redirect `pygotham.org/2015/` to `2015.pygotham.org`. We'd them also have to strip `/2015` from the beginning of the path. 

If you want to submit a pull request for that, please do.

**Comment by jonafato** [comment]
Bing provides the data to Duck Duck Go. I'm not sure how often their crawlers update, but once they do, the issue should resolve itself.

**Comment by dirn** [comment]
The search results Duck Duck Go seem to be behaving correctly now.
