### ISSUE TITLE
Allow a talk to be withdrawn

### ISSUE THREAD

**Issue by dirn** [PyGotham/pygotham#292]
From time to time people change their mind and lose interest in giving a talk. We should provide a way for them to mark the talk as withdrawn.

The ability to withdraw a talk should probably expire once the talk is marked as accepted or rejected. Removing a rejected talk doesn't do anything. Removing an accepted talk can cause problems with the schedule. Speakers should have to notify us that they can't give a talk once it's been accepted.

**Comment by jonafato** [comment]
I think this is a subset of #200.
