### ISSUE TITLE
Should we support more markup languages for talks?

### ISSUE THREAD

**Issue by jonafato** [PyGotham/pygotham#299]
Currently, we only support reST. Some submitters are more accustomed to markdown or plaintext. Should we add support for other languages?

**Comment by dirn** [comment]
My thinking is that if the reST parser fails, we should fall back to plain text.

**Comment by pathunstrom** [comment]
As a note, I tend to write my proposals in Markdown because it falls back to plain text well. I don't know if that helps the conversation?

**Comment by dirn** [comment]
@pathunstrom that is an _excellent_ point.

**Comment by pathunstrom** [comment]
Definitely more likely to use it if it has a preview since it's not a markup I know.
