### ISSUE TITLE
Sponsor model should support Twitter handles

### ISSUE THREAD

**Issue by jonafato** [PyGotham/pygotham#309]
Most sponsor companies have Twitter accounts. When we tweet about sponsorship (related: #244), it would be nice to at-mention the company. Adding a column to the Sponsor model makes it easier to work with this data in an automated / scheduled fashion.

Steps:
1. Add a column to the Sponsor model
2. Generate an alembic migration

**Comment by yahzaa** [comment]
I want to work on this.
