### ISSUE TITLE
Upgrade Flask-Security to 1.7.5, Flask-Login to 0.3.2

### ISSUE THREAD

**Issue by jonafato** [PyGotham/pygotham#317]
Flask-Security is currently [pinned to 1.7.4](https://github.com/PyGotham/pygotham/blob/0cd7dac58614fff222b7eaca62fb5fb07f2b9c7a/requirements.in#L17). The 1.7.5 release includes a number of improvements. Namely, this affects the PyGotham website in relation to #201.

This update will also require a Flask-Login upgrade. When Flask-Login made a [breaking change in the 0.3.0 release](https://github.com/maxcountryman/flask-login/blob/05b8f8602ee81f7d131607ab4757899883462ba6/CHANGES#L48-L50), Flask-Security dropped support for releases of Flask-Login before 0.3.0.

This change should consist of:
- Modifying all uses of `is_authenticated()` to be accessed as properties rather than called as methods
- Dropping the pinned versions on Flask-Security and Flask-Login from `requirements.in`
- Regenerating `requirements.txt` using `pip-compile --upgrade`
- Manually verifying that login, logout, and login-protected views work as expected

**Comment by spooskta** [comment]
Neat

**Comment by baoqchau** [comment]
Hello. Can I work on this issue?

**Comment by andela-ijubril** [comment]
Anyone working on this yet?

**Comment by baoqchau** [comment]
Yes, I am working on this issue. Having some trouble with running the website with Docker.

**Comment by dirn** [comment]
@bauqchau, what problems are you having?

**Comment by dirn** [comment]
@baoqchau what problems are you having?

**Comment by baoqchau** [comment]
I tried to follow the instructions to run the website with Docker. I installed Docker engine, docker compose and docker machine ( I'm using Linux Ubuntu so there is no Docker toolbox). However, there is error with creating host to run the website with the command ` docker-compose build`.

**Comment by dirn** [comment]
What is the error?

**Comment by baoqchau** [comment]
`ERROR: Couldn't connect to Docker daemon - you might need to run `docker-machine start default``
Then, I tried to run docker-machine but another error come:
`Host does not exist: "default"`.

**Comment by baoqchau** [comment]
updated: error fixed. It turned out that Docker run on linux need "sudo" to work. I will continue working on this issue.

**Comment by baoqchau** [comment]
Updated: All error fixed. I found the files containing `is_authenticated` as well. Will have a pull request soon.

**Comment by daneah** [comment]
@baoqchau are you still working on this one?

**Comment by baoqchau** [comment]
Yes, i will try to make a PR tonight. Busy with midterm for last weeks. Sorry for being late.

**Comment by daneah** [comment]
No problem on my end! Just checking 😄

**Comment by baoqchau** [comment]
Due to some business, I'm unable to finish this issue :( . If anyone interested, feel free to take it. Thanks a lot. 
P.S: should we update flask-login to 0.4.0, which is the newest version? Just a suggestion.

**Comment by jonafato** [comment]
@baoqchau Flask-Security does not yet support Flask-Login 0.4.0 (as specified by its `setup.py`), Flask-Login shouldn't be upgraded beyond 0.3.x. Once Flask-Security gains support for the latest version of Flask-Login, they can both be upgraded.
