### ISSUE TITLE
Site redirect WWW alias

### ISSUE THREAD

**Issue by jmeekr** [PyGotham/pygotham#319]
Problem:
Typing in `http://www.pygotham.org` redirects to `https://2016.www.pygotham.org`

Reason:
`pygotham.org` redirects to the most recent PyGotham event (2016 currently).  A `www` alias should also redirect to `2016.pygotham.org`.  If we're not going to support a `www` alias then we shouldn't redirect at all and provide an appropriate http response.

Corollary:
Perhaps the naked domain should not redirect, aside from http -> https.  The subdomain still exists, it just points to the same location

**Comment by dirn** [comment]
Somehow [this block](https://github.com/PyGotham/pygotham/blob/0cd7dac58614fff222b7eaca62fb5fb07f2b9c7a/server/nginx/pygotham.org.conf#L28-L29) is responding to more than just `pygotham.org`.

    server_name pygotham.org;
    return 302 https://2016.$host$request_uri;

**Comment by jmeekr** [comment]
I think the initial redirect on port 80 to 443 is capturing the `www` in the `$host`, and there is no explicit `www` in the server name lists.  I can't test it out right now, but perhaps we could rewrite if `$host` contains anything in front of it that's not an archive year.  Or just match the archive years first and rewrite everything else.

**Comment by dirn** [comment]
The initial redirect tells the browser to go from `www.pygotham.org:80` to `www.pygotham.org:443`. But when the browser makes the second request, none of the `server` blocks should pick it up. It should 404 (also not our desired behavior) because we don't list `www` or a wildcard anywhere.
