### ISSUE TITLE
Support public talk voting

### ISSUE THREAD

**Issue by dirn** [PyGotham/pygotham#324]
There has been talk amongst the PyGotham organizers about allowing the public to vote on talk submissions for some time (in fact, this was how things worked before this iteration on the website). The initial version of this should be pretty straight forward: any registered user can vote on any submitted proposal, giving it a thumbs up (+1), thumbs down (-1), or no vote (0). A score for the submission can be determined with the basic formula:

    (thumbs up - thumbs down) / (thumbs up + thumbs down + no votes)

This score can be used to help to guide the program committee through the talk selection process.

**Open questions**

* What information should be displayed? I believe the most likely candidates are:
  * `Talk.name`
  * `Talk.description`
  * `Talk.abstract`
  * `Talk.outline`
* Is #292 a prerequisite?
* Should we allow people to begin voting before the CFP closes? (If the answer is yes, there will be follow up questions.)

**Database schema changes**

In order to support voting, the following changes need to be made to the database:

* A new model (`Vote`) needs to be created. It should resemble

```
class Vote(Model):
    id = Column(Integer, primary_key=True)
    talk_id = Column(ForeignKey('talks.id'), nullable=False)
    user_id = Column(ForeignKey('users.id'), nullable=False)
    vote = Column(Integer, nullable=False)
    # perhaps some timestamps
```

* The `Event` model should be altered to include

```
    # perhaps a boolean field to represent whether or not the event allows voting
    voting_begins = Column(ArrowType)
    voting_ends = Column(ArrowType)
```

**Comment by dcrosta** [comment]
There are some pitfalls to the scoring formula having to do with talks that have uneven numbers of votes. A talk with a single upvote or downvote will look like 100% consensus that it's good or bad, respectively, and a talk with many votes might revert to the mean and get a score near 0.

I don't want to over-complicate things, but I think if we ask a statistician (like @jarfa with whom I used to work) they can suggest something a little less pothole-ey that doesn't add too much more complication. (I hope).

Certainly we should start with just being able to collect the votes -- applying a formula later ought to be simple. (I also hope we will be preserving a record of the votes, not just the sum of upvotes/downvotes/0-votes -- at minimum, this can be how you can enforce that no one can vote more than once per talk).

I'm interested in working on this, in case you can't tell 😄

**Comment by pathunstrom** [comment]
@dcrosta I would definitely think no matter what we do that we'd keep individual voting records in some format.

If we don't allow voting before CFP closes, we have the problem of reengaging members of the community to vote quickly enough to have meaningful data.

Of course if we do, there's the fact that earlier talks have an advantage based on engagement.

So I guess my big question is: How do we make this feature obvious and pull people in to take the time to read the proposals?

**Comment by dcrosta** [comment]
- Dan

**Comment by dcrosta** [comment]
My $0.02 -- open voting for a period of
time (1 week? 2 weeks?) after CFP closes and heavily promote it -- an email to all people who proposed, tweets, website.

**Comment by dirn** [comment]
>Certainly we should start with just being able to collect the votes

I hadn't really gotten too into the implementation details yet, but I went ahead and added a rough schema to the issue.

>If we don't allow voting before CFP closes, we have the problem of reengaging members of the community to vote quickly enough to have meaningful data.

This is definitely one of the concerns. As we've never done this (under the current system), it will really be on us to drive people to vote. It will be work. In addition to @dcrosta's suggestions, we can also reach out to past attendees.

>Of course if we do, there's the fact that earlier talks have an advantage based on engagement.

I would actually see this as a benefit. It would help encourage people to submit their proposals early. This would become more significant if we ever decide to add a feedback system.

The concern that I have with allowing the voting early is that someone can submit early, get a lot of votes (direction doesn't matter), and then alter their proposal. If this happens, what would we do? Nothing? Flush the votes? Alert people who voted? Would we need to determine the amount that changed? Fixing a word here and there would probably be too insignificant to take action.

I have more thoughts. I'll share them when I have some more time later.

**Comment by dcrosta** [comment]
>     voting_begins = Column(ArrowType)
>    voting_ends = Column(ArrowType)

We might just want `voting_active` that we control manually. Unless you want to start voting at like 3am or something, I'm not waking up for that :)

**Comment by dirn** [comment]
As the person who would (historically) be the one to check and uncheck the box, I prefer to let the site handle it for me. That's how we handle other parts of `Event` as well.

**Comment by jarfa** [comment]
Thanks for the mention, Dan.

Real quick on how I'd answer the question "how do we rank people by percentage when taking into account sample size" - I can think of 2 options.

1) Do an Empirical Bayes estimate - the TL;DR is it outputs a weighted average between the global average % and a particular talk's %, with the weights being a function of the sample size. More votes means less weight towards the global average. There's a great blog post about it [here](http://varianceexplained.org/r/empirical_bayes_baseball/).
Problem: to a lot of people this will feel like an arbitrary approach, even if you write out your process ahead of time.

2) Simple - only consider talks with over `n_cutoff` votes, where `n_cutoff` is some reasonable number based on our expectations. Then consider the % up without worrying any more about sample size. This may not feel as Statistically well-motivated as the previous option, but to most participants it'll feel less arbitrary. However much fun option#1 is - this isn't an area where we need to be statistically 100% correct.
Problem: we could drastically over/under-estimate the correct `n_cutoff`

**Comment by dcrosta** [comment]
@jarfa are confidence intervals not a thing that makes sense to do here? That's what I had in mind, but then again, I've always had some trouble grasping this stuff fully.

**Comment by jarfa** [comment]
You could build a (let's say) 90% confidence interval for each CFP, and say that you will rank CFPs based on the bottom edge of their interval. It's kinda similar but not identical in effect as the empirical bayes method. Whatever confidence interval method you choose, make sure it doesn't have 0 width when `(up_votes / total_votes) in (0.0, 1.0)`.

For the Empirical Bayes method: if a CFP has few total votes but a _high_ %, that % will be moved _down_ towards the mean. If a CFP has few total votes but a _low_ %, that % will be moved _up_ towards the mean. The amount of movement is inversely related to the number of votes - more votes, less movement.

For a confidence interval method: all CFP %'s will be move downwards, but those with fewer votes will move more.

That was probably a lot more than you cared to read, @dcrosta should know better than to ask me Stats questions. Again, I bet yall will just declare that only CFPs with `>= n_cutoff` votes will be counted, and that's not a terrible solution.

**Comment by dcrosta** [comment]
OK thanks for all the info @jarfa (and, yes, I should have known better than to ask you stats questions, how quickly we forget 😛 )

I also didn't mean to derail this ticket, which is about collecting votes, with discussions about how we might use them. My final thoughts here for now are mostly that we should not show people what the vote record is until after voting (if at all). To do so might influence their vote. We should show them their own vote so they can revise (again, during the voting window).

**Comment by dirn** [comment]
I don't think the scores get shown anywhere publicly. Speaking of showing things publicly, I don't know what the interface will look like. So far I've really only thought about mechanics.
