### ISSUE TITLE
Set password when creating users through the admin

### ISSUE THREAD

**Issue by dirn** [PyGotham/pygotham#80]
While the admin doesn't allow for direct editing of a user's password, creating a user should at least set it to something. Currently the password is null in the database. This causes a `TypeError` when the value (i.e., `None`) is hashed. This prevents these users from using the reset password functionality to set a password.

**Comment by jonafato** [comment]
If there's no existing desired implementation for this, I'm suggesting an approach based on [Django's](https://github.com/django/django/blob/e2d6e14662d780383e18066a3182155fb5b7747b/django/contrib/auth/hashers.py#L58-76) `make_password` behavior when passed `None` as the password. If there's no objection to this approach, I'll implement it.

**Comment by dirn** [comment]
How does the user get the password?

**Comment by jonafato** [comment]
I'd prefer to leave out the ability for an admin to set the password explicitly. Would setting the password to something unusable and automatically sending out a password reset link to users created via the admin be a reasonable middleground?

**Comment by dirn** [comment]
I prefer the reset link approach myself. Let's do it.
