### ISSUE TITLE
Convert "about" pages to database-backed reStructuredText content

### ISSUE THREAD

**Issue by jonafato** [PyGotham/pygotham#84]
This includes FAQ, privacy policies, etc. Doing this would also address #83, #24, possibly #59, and handle future issues like those. This also makes the site more reusable / less PyGotham-specific.

**Comment by djds23** [comment]
@dirn has there been any work done on this? I would love to help on this issue.

**Comment by dirn** [comment]
@jonafato?

**Comment by jonafato** [comment]
@djds23 I have a branch with an open PR (#91) pending further changes. Right now, it needs a better way to build out links in menus. Open to suggestions / additions.

Currently, it's not very flexible in terms of building out the nav. We could potentially live with that inflexibility and open up a new ticket to specifically address that issue if it's blocking something else.
