### ISSUE TITLE
Add license information to Code of Conduct

### ISSUE THREAD

**Issue by dirn** [PyGotham/pygotham#86]
The PyGotham Code of Conduct is based on the one found at http://geekfeminism.wikia.com/wiki/Conference_anti-harassment/Policy. Its license should be included on the page.

    This Code of Conduct was forked from the example policy from the Geek Feminism wiki, created by the Ada Initiative and other volunteers. which is under a Creative Commons Zero license.

The fork should also include license information (http://creativecommons.org/licenses/by/3.0/).

    PyGotham Code of Conduct by http://pygotham.org/about/code-of-conduct/ is licensed under a Creative Commons Attribution 3.0 Unported License.

**Comment by jonafato** [comment]
This is strictly a content issue and does not need any application-level work. As of the merging of PR #91, this issue no longer applies.
