### ISSUE TITLE
Automatically redirect to the current event

### ISSUE THREAD

**Issue by jonafato** [PyGotham/pygotham#88]
This ensures that links shared for a particular event will [not change](http://www.w3.org/Provider/Style/URI.html). See also: #87.

**Comment by jonafato** [comment]
This is going to cause some issues regarding how we currently resolve links to talks, speakers, etc. In those cases, if (for some reason) someone links to a talk but specifies the wrong year / event in the url, should we automatically redirect them to the correct one?

**Comment by dirn** [comment]
I think we need to put a bunch of 301 redirects in nginx that redirect the URLs for talks and speakers to the 2014 event. Generic URLs (e.g., talk list, schedule) can get 302s to the 2015 event. At some arbitrary point in the future we can remove them.

**Comment by jonafato** [comment]
We'll need those redirects, but I was more referring to the case where someone (for some reason) links to `/2015/talks/$talk_id_from_2014`. We could just throw a 404, but it may be nicer to the end user to redirect to the 2014 talk page. This is an unlikely edge case, so we can probably just go with the 404.

**Comment by dirn** [comment]
I would just make that a 404 because if someone is just guessing URLs and suddenly ends up on a different site they could be confused.

**Comment by jonafato** [comment]
:+1:

**Comment by dirn** [comment]
This was closed by #155
