### ISSUE TITLE
Make recording release on CFP checked by default

### ISSUE THREAD

**Issue by logston** [PyGotham/pygotham#97]
Right now it is unchecked.

**Comment by dirn** [comment]
This one is a little scary. This would force people to opt out of letting us use their content. We need to find out the legal implications of making such a switch.

**Comment by logston** [comment]
Sure is. I'd like to point out our copy that sits next the checkbox though:

> By submitting your talk proposal, you agree to give permission to Big Apple Py to record, edit, and release audio and/or video of your presentation. **If you do not agree to this, please uncheck this box.** See Recording Release for details.

**Comment by dirn** [comment]
Ha! Awesome. Then I say let's make the change!

**Comment by jonafato** [comment]
Can we make this something that has to be explicitly acknowledged instead? e.g. a radio input without a default?

**Comment by logston** [comment]
:+1:

**Comment by dirn** [comment]
Nope. We can't force them to accept it. There were folks last year who specifically said no.

**Comment by jonafato** [comment]
@dirn I'm not saying that we force them to accept it, I'm suggesting that we force them to explicitly choose yes or no. Radio inputs that start off unselected give us a way to validate that they've made a specific selection without biasing them with a default.

**Comment by dirn** [comment]
Oh, two radio buttons, one yes, one no. Got it. The language on the site went through the lawyer, so if we're telling people to opt out, we can.
