### ISSUE TITLE
Add phone number (required) and twitter (optional) handle to My Settings page. 

### ISSUE THREAD

**Issue by logston** [PyGotham/pygotham#98]

**Comment by dirn** [comment]
:+1: Twitter, :-1: phone number

**Comment by logston** [comment]
We had a lot of trouble locating people prior to their talks last time. Does any other conference require a phone number to submit proposal? If everyone else (a good number of other confs) get by without it, then I say we drop the need for this field.

**Comment by dirn** [comment]
I don't know of any that ask through the site. I know that PyCon encourages session runners to get contact information from their speakers. Perhaps it should be part of our process of notifying speakers of talk acceptance.

> Congratulations! Your talk has been accepted!! How the heck do we get in touch with you on the day of the conference?

**Comment by logston** [comment]
:+1:

**Comment by dirn** [comment]
This has been replaced by #131.
