### ISSUE TITLE
Add co-presentor instructions to CFP page. 

### ISSUE THREAD

**Issue by logston** [PyGotham/pygotham#99]
Add instructions for how to add a co-presentor to a talk submission.

**Comment by jonafato** [comment]
This depends on #100, correct?

**Comment by logston** [comment]
Yep. Is there a way I should label such a dependency?

**Comment by jonafato** [comment]
Not that I'm aware of. Just documenting that here for now.

**Comment by dirn** [comment]
It may also depend on #84 as well.

**Comment by jonafato** [comment]
@dirn possibly. If this is something that'll be enabled across the board, it should probably just go with the CFP form. This seems to be more about the feature's functionality than PyGotham's policies.

**Comment by dirn** [comment]
I was thinking it belonged here: http://pygotham.org/talks/call-for-proposals.

**Comment by jonafato** [comment]
Perhaps it's both? The instructions for how to find and add a user to the talk with the form and some PyGotham-specific "what this means" copy on that page?
